name: build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      libraryName: wi-pro-esp32-ftm
      tagName: 60abd3b7530a0c7990992757caa213ff378f97b3
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0 # <-- clone with complete history
          
      - uses: actions/checkout@v6
        with:
          repository: ucsdwcsng/wi-pro-esp32-ftm
          ref: ${{ env.tagName }}
          path: ${{ env.libraryName }}
          submodules: true
          fetch-depth: 0 # <-- clone with complete history

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          
      - run: |
          sudo chmod +x ./setup.sh

      - working-directory: ${{ env.libraryName }}
        run: ../setup.sh
          
      - working-directory: ${{ env.libraryName }}
        run: |
          set -e
          sudo chmod +x ./build_firmware.sh && \
          sudo chmod +x ./build_controller.sh && \
          ./build_firmware.sh && \
          ./build_controller.sh --target x86_64-pc-windows-gnu
          
      # ./wi-pro-esp32-ftm/firmware/bin:
      # bootloader.bin
      # firmware
      # firmware.bin
      # firmware.dis
      # partition-table.bin
      - run: |
           mkdir -pv dist/{firmware,controller} && \
           cp ${{ env.libraryName }}/firmware/bin/* ./dist/firmware/ && \
           cp ${{ env.libraryName }}/controller/controller* ./dist/controller/ && \
           cp ${{ env.libraryName }}/flash.sh ./dist/
           
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'dist'
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
    # # this action by default runs "idf.py build"
    #   - name: esp-idf build
    #     uses: espressif/esp-idf-ci-action@v1.2.0
    #     with:
    #       esp_idf_version: v5.5.2
    #       target: esp32c5

      - run: |
          ls -R
